### PR TITLE
Feat:  Ensured Table of Contents is sorted alphabetically | Made the Contribution.md and ReadMe.md more Appealing and Tech Savvy 🔥  

### PR DESCRIPTION
**Pull request by Chibuike-edmund**

### CODE REVIEW

**Comment by raymelon** [comment]
Thank you so much @Chibuike-edmund !

**Comment by PreciousEddy** [comment]
> Thank you so much @Chibuike-edmund !

@raymelon 

you haven't merged/closed the request yet

Wanna see if the whole thing was implemented real good

**Comment by raymelon** [comment]
> > Thank you so much @Chibuike-edmund !
> 
> @raymelon
> 
> you haven't merged/closed the request yet
> 
> Wanna see if the whole thing was implemented real good

Hi @Chibuike-edmund, yes I saw your contribution. I can merge this but it needs to be clear first how `update_readme()` will be implemented.

**Comment by Chibuike-edmund** [comment]
> > > Thank you so much @Chibuike-edmund !
> > 
> > 
> > @raymelon
> > you haven't merged/closed the request yet
> > Wanna see if the whole thing was implemented real good
> 
> Hi @Chibuike-edmund, yes I saw your contribution. I can merge this but it needs to be clear first how `update_readme()` will be implemented.

Oh true.

Lemme see if i can put that in the file, so if there any changes needed, you can go ahead and sort them out

**Comment by Chibuike-edmund** [comment]
@raymelon 

Just made an "update-Trial" seemed to work  though, Kindly check

**Comment by raymelon** [comment]
> @raymelon
> 
> Just made an "update-Trial" seemed to work though, Kindly check

Hold on, I'll merge and check it

**Pull request merged**
